### What is NumPy
NumPy is a Python library used for working with arrays

It also has functions for working in domain of **linear algebra**, **fourier transform** and **matrices**

### Why use Numpy
In Python, we have lists that serve the purpose of arrays, but they are slow to process

Numpy aims to provide an array object that is up to 50x faster than traditional Python lists

The array object in Numpy is called `ndarray`, it provides a lot of supporting functions that make working with `ndarray` very easy

### Why is Numpy faster than lists?
Numpy arrays are stored at one continous place in memory unlike lists, so processes can access and manipulate them very efficiently

This behavior is called locality of reference in computer science



### Numpy Getting Started?
Installation of NumPy

`pip install numpy`

Import NumPy

`import numpy`

Numpy is usually imported under the `np` alias

`import numpy as np`

Checking Numpy version by using `__version__()` attribute

`print(np.__version__)`

### Numpy Creating Arrays

Numpy is used to work with arrays. The array object in numpy is called `ndarray`

We can create a Numpy `ndarray` object by using the `array()` function

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


To create an `ndarray`, we can pass a list, tuple or any array-like object into the `array` method, and it will be converted into an `ndarray`

In [2]:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


### Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays)

### 0-D Arrays
0-D Arrays, or Scalars, are the elements in an array

Each value in an array is a 0-D array

In [3]:
import numpy as np
arr = np.array(42)
print(arr)
print(type(arr))

42
<class 'numpy.ndarray'>


### 1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array

In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


### 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array

These are often used to represent matrix or 2nd order tensors

In [5]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


### 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array

These are often used to represent a 3rd order tensor

In [6]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### Check Number of Dimensions?
Numpy arrays provides the `ndim` attribute that returns an integer that tells use how many dimensions the array have

In [7]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Higher Dimensional Arrays
An array can have any number of dimensions

When the array is created, you can define the number of dimensions by using the `ndmin` argument

In [8]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


### Access Array Elements 
Array indexing is the same as accessing an array element

You can access an array element by referring to its index number

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1

In [9]:
import numpy as np
arr = np.array([1, 2, 3, 4,])
print(arr[0])

1


### Access 2-D Arrays

To access elements from 2-D arrays we can use **comma** separated integers representing the dimension and the index of the element

In [10]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on the 1st row: ', arr[0, 1])

2nd element on the 1st row:  2


### Acess 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element

In [11]:
import numpy as np
arr = np.array([[[1, 2, 3],
                 [4, 5, 6],
                 [6, 7, 8],
                 [8, 9, 10]]])
print(arr[0, 1, 2])

6


### Negative Indexing
Use negative indexing to access an array from the end

In [12]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


### Slicing arrays
Slicing in python means taking elements from one given index to another given index

We pass slice instead of index like this `[start:end]`

We can also define the step like this `[start:end:step]`

In [13]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


### Negative Slicing
Use the minus operator to refer to an index from the end

In [14]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


### Step
Use the `step` value to determine the step of the slicing


In [15]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 8])
print(arr[1:5:2])

[2 4]


### Slicing 2-D Arrays

In [16]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [17]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


### Numpy Data Types
Numpy has some extra data types, and refer to data types with one character, like `i` for integers, `u` for unsigned integers

Below is a list of all data types in NumPy and the characters used to represent them

- `i` - integer
- `b` - boolean
- `u` - unsigned integer
- `f` - float
- `c` - complex float
- `m` - timedelta
- `M` - datetime
- `O` - object
- `S` - string
- `U` - unicode string
- `V` - fixed chunk of memory for other type ( void ) 

### Checking the Data Type of an Array
The Numpy array object has a property called `dtype` that returns the data type of the array


In [18]:
import numpy as np
arr = np.array([1, 2, 3, ])
print(arr.dtype)

int32


In [20]:
import numpy as np
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


### Creating Arrays with a Defined Data Type
We use the `array()` function to create arrays, this function can take an optional argument: `dytpe` that allows us to define the expected data type of the array elements

In [23]:
import numpy as np
arr = np.array([12, 22, 32, 42], dtype='S')
print(arr, arr.dtype)

[b'12' b'22' b'32' b'42'] |S2


### Converting Data Type on Existing Arrays
The best way to change the data type of an existing array, is to make a copy of the array with the `astype()` method

The `astype()` function creates a copy of the array, and allows you to specify the data type as a parameter

The data type can be specified using a string, like `f` for float, `i` for integer etc. or you can use the data type directly like float for `float` and `int` for `integer`

In [25]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1, 4.1, 5.1])
newarr = arr.astype('i')
print(arr.dtype)
print(newarr.dtype)

float64
int32


In [27]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1, 4.1, 5.1])
newarr = arr.astype(int)
print(arr.dtype)
print(newarr.dtype)

float64
int32


### Numpy Array Copy vs View
The main difference between a copy and a view of an array is that *the copy is a new array*, and *the view is just a view of the original array*

The *copy* *owns the data* and any changes made to the copy will *not affect* original array, and any changes made to the original array will not affect the copy

The *view* does *not own the data* and any changes made to the view will *affect* the original array, and any changes made to the original array will affect the view

### Copy
The copy SHOULD NOT be affected by the changes made to the original array.

In [28]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


### View
The view SHOULD be affected by the changes made to the original array.

In [29]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


### Check if Array Owns its Data
Every NumPy array has the attribute `base` that returns None if the array owns the data.

Otherwise, the `base` attribute refers to the original object.

In [30]:
import numpy as np
arr = np.array([1, 2, 3, 4])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4]


### Shape of an Array
The shape of an array is the number of elements in each dimension

NumPy arrays have an attribute called `shape` that returns a tuple with each index having the number of corresponding elements

In [33]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.shape)

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(4,)
(2, 4)


### Numpy Array Reshaping

Reshaping means changing the shape of an array

The shape of an array is the number of elements in each dimension

By reshaping we can add or remove dimensions or change number of elements in  each dimension

### Reshape from 1-D to 2-D

In [35]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Reshape From 1-D to 3-D

In [36]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Check if the returned array from reshaped array is a copy or view

In [39]:
import numpy as np
arr = np.array(range(1, 9))
newarr = arr.reshape(2, 4)
print(newarr.base)
newarr[0, 0] = 0
print(arr)

[1 2 3 4 5 6 7 8]
[0 2 3 4 5 6 7 8]


The reshaped array is a view, so any change from the original array affect the view array

### Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the `reshape` method.

Pass -1 as the value, and NumPy will calculate this number for you.

Note: We can not pass -1 to more than one dimension

In [41]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array

We can use the `reshape(-1)` to do this

In [42]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


### Numpy Array Iterating
Iterating means going through elements one by one

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

In [43]:
import numpy as np
arr = np.array([1, 2, 3])
for x in arr:
    print(x)

1
2
3


### Iterating 2-D Arrays
If we iterate on a *n-D* array, it will go through *n-1th* dimension one by one

To return the actual values, the scalars, we have to iterate the arrays in each dimension.

In [44]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


### Iterating Arrays Using nditer()
The function nditer() is a helping function that can be used from very basic to very advanced iterations

#### Iterating on Each Scalar Element


In [45]:
import numpy as np
arr = np.array([[[1, 2,], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


#### Iterating Array With Different Data Types
We can use `op_dtypes` argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called **buffer**, and in order to enable it in nditer() we pass `flags=['buffered']`.

In [46]:
import numpy as np
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


#### Iterating With Different Step Size
We can use fitering and followed by iteration

In [48]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


### Enumerated Iteration Using `ndenumerate()`
Enumeration means mentioning sequence number of somethings one by one

Sometimes we require corresponding index of the element while iterating, the `ndenumerate()` method can be used for those usecases

In [49]:
import numpy as np
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [50]:
import numpy as np
arr = np.array([[1, 2, 3,], [4, 5, 6]])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


### Numpy Joining Array

Joining means putting contents of two or more arrays in a single array

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes

We pass a sequence of arrays that we want to join to the `concatenate()` function, along with the axis. If axis is not explicitly passed, it is taken as 0

In [51]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [54]:
import numpy as np
arr1 = np.array([[1, 2,], [3, 4]])
arr2 = np.array([[4, 5], [5, 6]])
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2]
 [3 4]
 [4 5]
 [5 6]]
[[1 2 4 5]
 [3 4 5 6]]


### Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis

We can concatenate two 1-D arrays along the second axis which would result i putting the one over the other

We pass a sequence of arrays that we want to join to the `stack()` method along with the axis. If axis is not explicitly passed it is taken as 0

In [62]:
import numpy as np
arr1 = np.array([1, 5])
arr2 = np.array([6, 4])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 6]
 [5 4]]


### Stacking Along Rows
Numpy provides a helper function `hstack()` to stack along rows

In [57]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


### Stacking Along Columns
Numpy provides a helper function `vstack()` to stack along columns

In [59]:
import numpy as np
arr1 = np.array((1, 2, 3))
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


### Numpy Splitting Array
We use `array_split()` for splitting arrays, we pass it the array we want to split and the number of splits

The return value of the `array_split()` method is an array containing each of the split as an array.

If you split an array into arrays, you can access them from the result just like any array element

In [63]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


If the array has less elements than required, it will adjust from the end accordingly.

In [65]:
import numpy as np
arr = np.array(range(1, 7))
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


#### Splitting 2-D arrays
Use the same syntax when splitting 2-D arrays.

Use the `array_split()` method, pass in the array you want to split and the number of splits you want to do.

In [67]:
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In addition, you can specify which axis you want to do the split around.

In [68]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


An alternate solution is using `hsplit()` to split the 2-D array

In [69]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


Note: Similar alternates to `vstack()` and `dstack()` are available as `vsplit()` and `dsplit()`.

### Numpy Search Arrays
You can search an array for a certain value, and return the indexes that get a match

To search an array, use the `where()` method

In [74]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)
print(type(x))
print(x[0])

(array([3, 5, 6], dtype=int64),)
<class 'tuple'>
[3 5 6]


In [76]:
import numpy as np
arr = np.array(range(1, 8))
x = np.where(arr % 2 == 0)
print(x)

(array([1, 3, 5], dtype=int64),)


### Search Sorted
There is a method called `searchsorted()` which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order

In [80]:
import numpy as np
arr = np.array([6, 7, 8, 9,])
x = np.searchsorted(arr, 7)
print(x)

1


The method starts the search from the left and returns the first index where the number 7 is no longer larger than the next value.

#### Search From the Right Side

By default the left most index is returned, but we can give side='right' to return the right most index instead.

In [81]:
import numpy as np
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)

2


#### Numpy Sorting Arrays
Sorting means putting elements in an *ordered sequence*.

**Ordered sequence** is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called `sort()`, that will sort a specified array.


In [82]:
import numpy as np
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


Note: This method returns a copy of the array, leaving the original array unchanged.

In [84]:
import numpy as np
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [85]:
import numpy as np
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


### Sorting a 2-D Array
If you use the `sort)` method on a 2-D array, both arrays will be sorted

In [86]:
import numpy as np
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


### Numpy Filter Array
Getting some elements out of an existing array and creating a new array out of them is called *filtering*.

In NumPy, you filter an array using a *boolean index list*.

A *boolean index list* is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [87]:
import numpy as np
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


### Creating Filter Directly From Array
We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

In [88]:
import numpy as np
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]
