# Random Numbers in Numpy

Random numbers generated through a generation algorithm are called pseudo random.

Numpy offers the `random` module to work with random numbers

Use the function `random.randint(n)` to generate a random integer

The `randint()` method takes a `size` parameter where you can specify the shape of an array

In [3]:
from numpy import random
x = random.randint(100)
print(x)

x = random.randint(100, size=(5, ))
print(x)

93
[92 82 59 44 12]


Use the function `random.rand()` method returns a random float between 0 and 1

The `rand()` method also allows you to specify the shape of the array

In [7]:
from numpy import random
x = random.rand()
print(x)

x = random.rand(5, 3)
print(x)

0.755199745765094
[[0.58761663 0.18575057 0.44691459]
 [0.07238237 0.44684984 0.33257541]
 [0.22720324 0.68077878 0.16434694]
 [0.81970704 0.5316681  0.5084688 ]
 [0.80764673 0.97370721 0.262455  ]]


### Generate Random Number From Array

The `random.choice()` method allows you to generate a random value based on an array of values

The `random.choice()` method takes an array as a parameter and randomly returns one of the values


In [8]:
from numpy import random
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[3 3 9 5 5]
 [5 9 9 3 5]
 [5 7 3 9 5]]
